### ISSUE TITLE
build errors following tutorial

### ISSUE THREAD

**Issue by omulriain** [rubygarage/nextjs6-graphql-client-tutorial#28]
Is this tutorial still up to date? I really want this to wok.

at first I was getting errors saying:
Cannot find module 'babel-preset-env' that I resolved with yarn add babel-preset-env -D
Cannot find module 'babel-preset-stage-0' I resolved with yarn add babel-preset-stage-0 -D

now I get the following Error: Error: Plugin/Preset files are not allowed to export objects, only functions. In D:\projects\princigration\node_modules\babel-preset-stage-0\lib\index.js

here is my stack trace.

yarn run v1.22.10
$ start-storybook -p 9001 -c .storybook
info @storybook/react v6.1.11
info
info => Loading presets
info => Loading presets
info => Loading custom babel config
info => Loading custom babel config
info => Loading 1 config file in ".storybook"
(node:19584) DeprecationWarning: Configuration files such as "config", "presets" and "addons" are deprecated and will be removed in Storybook 7.0.
Read more about it in the migration guide: https://github.com/storybookjs/storybook/blob/master/MIGRATION.md#to-mainjs-configuration
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Using default Webpack setup
webpack built fb4bbd7f82d5771b1e7e in 4389ms
× ｢wdm｣: Hash: fb4bbd7f82d5771b1e7e
Version: webpack 4.44.2
Time: 4389ms
Built at: 01/02/2021 11:12:03 AM
                                          Asset       Size        Chunks                                Chunk Names
                                    iframe.html   4.38 KiB                [emitted]
            main.fb4bbd7f82d5771b1e7e.bundle.js   6.32 KiB          main  [emitted] [immutable]         main
        main.fb4bbd7f82d5771b1e7e.bundle.js.map  231 bytes          main  [emitted] [dev]               main
    runtime~main.fb4bbd7f82d5771b1e7e.bundle.js   33.5 KiB  runtime~main  [emitted] [immutable]         runtime~main
runtime~main.fb4bbd7f82d5771b1e7e.bundle.js.map   34.7 KiB  runtime~main  [emitted] [dev]               runtime~main
    vendors~main.fb4bbd7f82d5771b1e7e.bundle.js    799 KiB  vendors~main  [emitted] [immutable]  [big]  vendors~main
vendors~main.fb4bbd7f82d5771b1e7e.bundle.js.map    767 KiB  vendors~main  [emitted] [dev]               vendors~main
Entrypoint main [big] = runtime~main.fb4bbd7f82d5771b1e7e.bundle.js runtime~main.fb4bbd7f82d5771b1e7e.bundle.js.map vendors~main.fb4bbd7f82d5771b1e7e.bundle.js vendors~main.fb4bbd7f82d5771b1e7e.bundle.js.map mai
n.fb4bbd7f82d5771b1e7e.bundle.js main.fb4bbd7f82d5771b1e7e.bundle.js.map
[0] multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/config.js-genera
ted-config-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined 76 bytes {main} [built]
[./.storybook/config.js-generated-config-entry.js] 1.7 KiB {main} [built] [failed] [1 error]
[./.storybook/storybook-init-framework-entry.js] 1.7 KiB {main} [built] [failed] [1 error]
[./node_modules/@storybook/core/dist/server/common/polyfills.js] 120 bytes {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/preview/globals.js] 93 bytes {vendors~main} [built]
[./node_modules/airbnb-js-shims/index.js] 40 bytes {vendors~main} [built]
[./node_modules/core-js/features/symbol/index.js] 359 bytes {vendors~main} [built]
[./node_modules/global/window.js] 232 bytes {vendors~main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {vendors~main} [built]
[./node_modules/regenerator-runtime/runtime.js] 24 KiB {vendors~main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.17 KiB {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined] (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined 7.68 KiB {vendors~main} [built]
[./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.35 KiB {vendors~main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {vendors~main} [built]
    + 319 hidden modules

ERROR in ./.storybook/storybook-init-framework-entry.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In D:\projects\princigration\node_modules\babel-preset-stage-0\lib\index.js
    at createDescriptor (D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:58:104
    at cachedFunction (D:\projects\princigration\node_modules\@babel\core\lib\config\caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (D:\projects\princigration\node_modules\gensync\index.js:251:28)
    at sync (D:\projects\princigration\node_modules\gensync\index.js:89:14)
    at presets (D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:29:84)
    at mergeChainOpts (D:\projects\princigration\node_modules\@babel\core\lib\config\config-chain.js:416:26)
    at D:\projects\princigration\node_modules\@babel\core\lib\config\config-chain.js:374:7
    at Generator.next (<anonymous>)
    at buildRootChain (D:\projects\princigration\node_modules\@babel\core\lib\config\config-chain.js:73:36)
    at buildRootChain.next (<anonymous>)
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/config.js-generat
ed-config-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[2]

ERROR in ./.storybook/config.js-generated-config-entry.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In D:\projects\princigration\node_modules\babel-preset-stage-0\lib\index.js
    at createDescriptor (D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:58:104
    at cachedFunction (D:\projects\princigration\node_modules\@babel\core\lib\config\caching.js:62:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (D:\projects\princigration\node_modules\gensync\index.js:251:28)
    at sync (D:\projects\princigration\node_modules\gensync\index.js:89:14)
    at presets (D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:29:84)
    at mergeChainOpts (D:\projects\princigration\node_modules\@babel\core\lib\config\config-chain.js:416:26)
    at D:\projects\princigration\node_modules\@babel\core\lib\config\config-chain.js:374:7
    at Generator.next (<anonymous>)
    at buildRootChain (D:\projects\princigration\node_modules\@babel\core\lib\config\config-chain.js:73:36)
    at buildRootChain.next (<anonymous>)
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/config.js-generat
ed-config-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[3]
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.18 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 1.97 KiB {HtmlWebpackPlugin_0} [built]

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

× ｢wdm｣: Hash: 29f99b95065ab3d46a65
Version: webpack 4.44.2
Time: 5103ms
Built at: 01/02/2021 11:12:04 AM
                                      Asset      Size        Chunks                                Chunk Names
                                 index.html  3.17 KiB                [emitted]
        main.cfcd000107e8882fa903.bundle.js  3.35 KiB          main  [emitted] [immutable]         main
runtime~main.99691078705b39185f99.bundle.js  6.12 KiB  runtime~main  [emitted] [immutable]         runtime~main
vendors~main.60915daf9108aa5eef1c.bundle.js  6.05 MiB  vendors~main  [emitted] [immutable]  [big]  vendors~main
Entrypoint main [big] = runtime~main.99691078705b39185f99.bundle.js vendors~main.60915daf9108aa5eef1c.bundle.js main.cfcd000107e8882fa903.bundle.js
[0] multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js ./.storybook/generated-refs.js 52 bytes {main} [built]
[./.storybook/generated-refs.js] 1.69 KiB {main} [built] [failed] [1 error]
[./node_modules/@storybook/addons/dist/public_api.js] 2.56 KiB {vendors~main} [built]
[./node_modules/@storybook/api/dist/index.js] 21.7 KiB {vendors~main} [built]
[./node_modules/@storybook/channel-postmessage/dist/index.js] 13.5 KiB {vendors~main} [built]
[./node_modules/@storybook/core-events/dist/index.js] 4.64 KiB {vendors~main} [built]
[./node_modules/@storybook/core/dist/client/manager/conditional-polyfills.js] 2.56 KiB {vendors~main} [built]
[./node_modules/@storybook/core/dist/client/manager/index.js] 521 bytes {vendors~main} [built]
[./node_modules/@storybook/core/dist/client/manager/provider.js] 5.04 KiB {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/common/polyfills.js] 120 bytes {vendors~main} [built]
[./node_modules/@storybook/ui/dist/index.js] 3.54 KiB {vendors~main} [built]
[./node_modules/airbnb-js-shims/index.js] 40 bytes {vendors~main} [built]
[./node_modules/core-js/features/symbol/index.js] 359 bytes {vendors~main} [built]
[./node_modules/global/window.js] 232 bytes {vendors~main} [built]
[./node_modules/regenerator-runtime/runtime.js] 24 KiB {vendors~main} [built]
    + 1459 hidden modules

ERROR in ./.storybook/generated-refs.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In D:\projects\princigration\node_modules\babel-preset-stage-0\lib\index.js
    at createDescriptor (D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (D:\projects\princigration\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
    at mergeChainOpts (D:\projects\princigration\node_modules\@babel\core\lib\config\config-chain.js:416:26)
    at D:\projects\princigration\node_modules\@babel\core\lib\config\config-chain.js:374:7
    at Generator.next (<anonymous>)
    at loadFileChain (D:\projects\princigration\node_modules\@babel\core\lib\config\config-chain.js:228:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (D:\projects\princigration\node_modules\@babel\core\lib\config\config-chain.js:135:29)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (D:\projects\princigration\node_modules\@babel\core\lib\config\partial.js:101:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at D:\projects\princigration\node_modules\@babel\core\lib\config\partial.js:140:25
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/client/manager/index.js ./.storybook/generated-refs.js main[2]
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.18 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 1.97 KiB {HtmlWebpackPlugin_0} [built]
WARN Force closed preview build

**Comment by omulriain** [comment]
okay I was able to get past the error by grabbing your package.json file from here and running 'yarn install' before running 'yarn storyboard' You might add a hint for people running into trouble at this step if Im not the only one.
